### ISSUE TITLE
Cannot scroll through the result pane of an subscription

### ISSUE THREAD

**Issue by iagobruno** [prisma-labs/graphql-playground#1021]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [x] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
Windows 10

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
1.7.x

#### What is the expected behavior?
Can scroll the result panel to see all events.

#### What is the actual behavior?
When I try to use the mouse wheel nothing happens.

#### What steps may we take to reproduce the behavior?
Just make a simple subscription query and get some events to see the problem.

#### Idea of how to solve the problem:
Currently the result panel has `height: auto`, you have to do the height calculation that the panel should have using javascript when the app is mounted or make the editor container have the height you want/possible and make the result panel have `height: 100%`.

**Comment by loudmouth** [comment]
Also experiencing this problem.

**Comment by phanatuan** [comment]
Me too!

**Comment by ksugiarto** [comment]
No update on this issue? Then how did you guys use this for Subscription all this long? Any workaround?

**Comment by smeijer** [comment]
> Any workaround?

<kbd>F5</kbd>

**Comment by iagobruno** [comment]
For now, the only solution is install [an extension](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne) to inject this css into localhost pages.

```css
.graphiql-wrapper>div:first-child>div:first-child>div:nth-child(2)>div:nth-child(2) {
  height: 100%
}
```

**Comment by smeijer** [comment]
@iagobruno , I can recommend adding `display: flex` and `flex-direction: column-reverse` to that snippet, to inverse the direction. This way you'll always have the most recent data on top. Making it unnecessary to scroll:

```css
display: flex;
flex-direction: column-reverse;
```

**Comment by iagobruno** [comment]
@smeijer I tested your recommendation but it causes a scrollbar bug when a new result is added (I have no idea why), but the [overflow-anchor](https://css-tricks.com/almanac/properties/o/overflow-anchor/) property will make the last added item always visible if you scroll to extreme bottom.

**Comment by vojtapol** [comment]
This is broken in **GraphQL Playground HTML** too. Any idea how to temporarily fix it there?

**Comment by vizo** [comment]
Anything new on this?

**Comment by fitalefi** [comment]
+1

**Comment by adrianoresende** [comment]
+1

**Comment by arnasledev** [comment]
still a problem..

**Comment by AkashRajpurohit** [comment]
Why is the issue closed, still facing this issue

**Comment by beeman** [comment]
The scrolling issue is fixed in this version, however it issue very possible that the GraphQL server you are using is using a different version of this library. I know that for instance Apollo maintains their own for which still has the bug.

**Comment by AkashRajpurohit** [comment]
> The scrolling issue is fixed in this version, however it is very possible that the GraphQL server you are using is using a different version of this library. I know that for instance Apollo maintains their own for which still has the bug.

@beeman Yes, I am using Apollo maybe that's why the issue still persists in the playground version there. 

Can you tell me where should I reach for to get this issue solved?
