### ISSUE TITLE
compilation errors in `node_modules` ( getAutocompleteSuggestions.js ) 

### ISSUE THREAD

**Issue by abisalehalliprasan** [prisma-labs/graphql-playground#1235]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [x] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
Mac OS ( 10.13.6 )

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
`"graphql-playground-react": "^1.7.23"`

#### What is the expected behavior?
When I compile my project I am getting the error as explained below .: 

#### What is the actual behavior?
I see compilation errors about loading appropriate webpack loaders. Not sure If I am missing something : 

Here is the output from my compilation
```
 ›   Error: ./node_modules/graphql-language-service-interface/esm/getAutocompleteSuggestions.js 35:51
 ›   Module parse failed: Unexpected token (35:51)
 ›   You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
 ›   |                 label: argDef.name,
 ›   |                 detail: String(argDef.type),
 ›   >                 documentation: argDef.description ?? undefined,
 ›   |                 kind: CompletionItemKind.Variable,
 ›   |             })));
 ›     @ ./node_modules/graphql-language-service-interface/esm/index.js 2:0-45 2:0-45
 ›     @ ./node_modules/codemirror-graphql/lint.js
 ›     @ ./node_modules/graphql-playground-react/lib/components/Playground/QueryEditor.js
 ›     @ ./node_modules/graphql-playground-react/lib/components/Playground/GraphQLEditor.js
 ›     @ ./node_modules/graphql-playground-react/lib/lib.js
```
Here's my  webpack.config.js : 
```
  rules: [
    {
      test: /\.mjs$/,
      use: "raw-loader",
      include: /node_modules/,
      type: "javascript/auto",
    },
  ],
  resolve: {
    extensions: [".js", ".jsx", ".json", ".css", ".mjs"],
  },
``` 

I tried to add this to `package.json` based on some findings on other repo but to no avail : 
```
  "resolutions": {
    "graphql-language-service-interface": "2.4.0-alpha.8"
  }
```

#### What steps may we take to reproduce the behavior?
I followed the instructions listed [here](https://github.com/prisma-labs/graphql-playground#as-react-component)

Any help would be appreciated. Thanks!

**Comment by acao** [comment]
this was a bug in graphiql repo we fixed. should be reflected in latest playground release

**Comment by timkovik** [comment]
>   "resolutions": {
    "graphql-language-service-interface": "...."
  }

**Comment by abisalehalliprasan** [comment]
@acao @timkovik : I am still getting this error with the latest release for : 
`graphql-playground-react` : `^1.7.27`

I am on node v10.15.2 if that helps. Any insights guys ?

**Comment by allanmaclean** [comment]
Having the same issue - did you happen to get anywhere with it?
