### ISSUE TITLE
GraphQL Playground significant battery drain

### ISSUE THREAD

**Issue by heymartinadams** [prisma-labs/graphql-playground#653]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [x] GraphQL Playground HTML

#### Observation
This isn’t an issue, just a helpful observation I wanted to pass onto the community: noticed how running GraphQL Playground in Chrome, even when not using it, quickly depleted my laptop’s battery. But not so with the electron standalone version of the GraphQL Playground.

## Energy Impact
GraphQL Playground in Chrome:
<img width="771" alt="withgqlp" src="https://user-images.githubusercontent.com/11673745/38997084-ea3e6278-43ec-11e8-9c10-094f5878f8f0.png">
Chrome without GraphQL Playground:
<img width="765" alt="withoutgqlp" src="https://user-images.githubusercontent.com/11673745/38997159-1a8fcc14-43ed-11e8-8a6b-8c4844461d16.png">
GraphQL Playground (standalone):
<img width="496" alt="withgqlp-standalone" src="https://user-images.githubusercontent.com/11673745/38997112-f8b0a834-43ec-11e8-92c9-ad4178b93543.png">

**Comment by heymartinadams** [comment]
Oops, spoke too soon! Apparently also in the standalone version...
<img width="702" alt="gqlp-standalone" src="https://user-images.githubusercontent.com/11673745/38998301-8f554a2c-43ef-11e8-8a57-c36c704b1482.png">

**Comment by timsuchanek** [comment]
Thanks for reporting @heymartinadams ! Which version of the Playground are you using? We had similar issues in previous versions.

**Comment by heymartinadams** [comment]
@timsuchanek v1.5.4

**Comment by heymartinadams** [comment]
@schickling it appears to occur always, once a connection to the server has been established.

**Comment by schickling** [comment]
@heymartinadams can you record a quick video screencast (I recommend [Loom](https://www.useloom.com/my-videos)) where you launch the Playground and reproduce the behaviour?

**Comment by schickling** [comment]
Hmm that's weird. For me I don't get this kind of CPU utilization despite running the same query on the same endpoint + using PG version 1.6.3

![image](https://user-images.githubusercontent.com/1567498/39523315-786b047a-4e15-11e8-81fe-eb33abbbae29.png)

Can you completely wipe the Playground and re-install?

**Comment by heymartinadams** [comment]
@schickling where’s access to v1.6.3? Only seeing 1.5.6: https://github.com/graphcool/graphql-playground/releases

Same issue with v1.5.6, despite completely wiping PG.
<img width="820" alt="playground" src="https://user-images.githubusercontent.com/11673745/39523532-4171b346-4e16-11e8-9e57-e6330c5ce6ab.png">

**Comment by schickling** [comment]
Oh sorry, the versioning scheme is a bit confusing right now. There are two versions:

1. Electron app: 1.5.6 
2. Wrapped react app 1.6.3 (see in settings tab)

![image](https://user-images.githubusercontent.com/1567498/39523897-76fa9c0c-4e17-11e8-8561-1a6b3291c12b.png)
![image](https://user-images.githubusercontent.com/1567498/39523919-89ca1ac4-4e17-11e8-9566-76b9410511ef.png)

@heymartinadams do you have the option to try out the same on a different machine as well?

**Comment by heymartinadams** [comment]
@schickling not at the moment. Probably in a week from now.

**Comment by heymartinadams** [comment]
Mmh. Restarted PG again and this time it appears to be ok! Not sure what happened, @schickling, or why. Closing this unless it comes up again.

**Comment by heymartinadams** [comment]
Sometimes, too, I enter the correct server address `https://afgen.us` and the schema keeps spinning. Restarting PG appears to then fix the issue.

**Comment by lorensr** [comment]
I also see high CPU usage when the server cannot be reached.

![image](https://user-images.githubusercontent.com/251288/43755299-3fd99144-99dd-11e8-967c-84ceb80f76fd.png)

![image](https://user-images.githubusercontent.com/251288/43755307-4d649962-99dd-11e8-9ea3-586d1292ea84.png)

In the console, every second there are 5 errors:

![image](https://user-images.githubusercontent.com/251288/43755330-6d8e90da-99dd-11e8-8817-c4adc8a830bd.png)

**Comment by lorensr** [comment]
I updated to the latest npm version and it no longer happens. Looks like it was fixed by 

https://github.com/prismagraphql/graphql-playground/issues/627

**Comment by calendee** [comment]
I'm using the latest GraphQL Playground (1.8.7) and am still seeing high CPU usage.

<img width="993" alt="graphql-playground-high-usage" src="https://user-images.githubusercontent.com/57374/51837997-ad6f4700-22ca-11e9-8bcd-0eb17d4e4afa.png">

**Comment by JClackett** [comment]
I'm having the same issues, happening on the latest demo version: https://www.graphqlbin.com/v2/6RQ6TM

when i turn polling off in settings it seems to calm down

**Comment by Cerberus** [comment]
In my case, I got some clues.

Open `setting` tab. It drains cpu normally.
<img width="546" alt="too low" src="https://user-images.githubusercontent.com/9087409/59777019-06716300-92de-11e9-9b3a-f8e84540fa10.png">

But, open `editor` tab. It drains cpu too high.
<img width="533" alt="too high" src="https://user-images.githubusercontent.com/9087409/59777020-06716300-92de-11e9-96d9-b5ee4d2ac0ae.png">

version 1.8.10

**Comment by taylorgoolsby** [comment]
Whenever I have graphql playground open, I notice "WindowServer" and "Google Chrome Helper" have unusually high CPU usage. It stays like that as long as I have the tab open. As soon as I close it, or switch to a different tab, it's back to normal.

![image](https://user-images.githubusercontent.com/14286600/60751509-10949200-9f6b-11e9-97f3-70511abe9e7c.png)

**Comment by blaiprat** [comment]
I've been struggling meanwhile working on a high dpi display and the playground. Today I did a bit of research and found out that the pulsating dot animation is what triggers the high cpu usage. Once you remove it form the page the page stops refreshing at 60fps and the Windows Server process stops using so much CPU

So as a temporary fix disabling the schema polling removes the dot and decreases CPU usage
Here's a gif with a quick test on this
![ezgif-2-f69a739c86ac](https://user-images.githubusercontent.com/723386/62362786-a8a77c00-b515-11e9-8bf2-b144e46b6444.gif)

**Comment by waynerob** [comment]
Good catch blaiprat!  I had no idea that a CSS-specified animation could be so expensive.  Apparently as developers we should scrutinize the use of any such animations in our pages.  The notion of CSS animations being far less costly than old JS-based hacks seems to be erroneous.

**Comment by bibendi** [comment]
Confirm @blaiprat's workaround. After I've disabled schema pooling, my laptop CPU LA gets down from 4 to 1.

**Comment by adrianoresende** [comment]
@heymartinadams Alerting you to the significant problem.

**Comment by heymartinadams** [comment]
Good to know, @adrianoresende. Will close this issue. 🙌🏼
